* Basic Concepts

** 1.1 Algorithms

- Algorithm ::
  Is a generic set of steps to solve a defined category of problem. First began
  be used in order to refer to Euclid's steps to find the Greatest Common Divisor
  of two numbers

#+begin_src python
def gcd(m, n):
  r = m // n
  if r == 0:
    return n
  else:
    return gcd(n, r)
#+end_src

Algorithms are defined by first stating the sort of problem that is to be solved.
Then input data is defined, what quantity and type. Next the steps involved in
are stated, with any conditionals and branches.

The first step to proving the correctness of an algorithm is to manually try a simple
test case, whether it is small bits of data or manually in pencil and paper.

An algorithm has certain properties

1. It must always terminate
2. Defined precisely for all forms of data that it inputs. Can be defined with
   programming language
3. An algorithm must have inputs
4. Produce output
5. Good Algorithms must be proven to yield the correct results, at least good enough

**** Defining Computational Methods with Set Theory
