* Basic Concepts

** 1.1 Algorithms

- Algorithm ::
  Is a generic set of steps to solve a defined category of problem. First began
  be used in order to refer to Euclid's steps to find the Greatest Common Divisor
  of two numbers

#+begin_src scheme
(define (gcd m n)
  (let ((r (// m n)))
       (if (== r 0)
           n
           (gcd n r))))
#+end_src

Algorithms are defined by first stating the sort of problem that is to be solved.
Then input data is defined, what quantity and type. Next the steps involved in
are stated, with any conditionals and branches.

The first step to proving the correctness of an algorithm is to manually try a simple
test case, whether it is small bits of data or manually in pencil and paper.

An algorithm has certain properties

1. It must always terminate
2. Defined precisely for all forms of data that it inputs. Can be defined with
   programming language
3. An algorithm must have inputs
4. Produce output
5. Good Algorithms must be proven to yield the correct results, at least good enough

**** Defining Computational Methods with Set Theory

The book goes on to give a definition of Algorithms using tools from set theory.
A computational method is a somewhat universe of sets and subsets that define an
algorithm. A quadruped with terms

\begin{equation}
(Q, I, \Omega, f)
\end{equation}

F denotes the computational rule, the algorithm, set of steps in order to
compute $\Omega$ which is the set of all possible outputs of f. I denote
all possible inputs to f and Q denotes all possible inner states of the function
given the input and the output, all the possible machine states required in
order to compute problem.

Set I is an ordered set where

\begin{equation}
x_0 = x
\end{equation}

Here x is any number. All the other items in sequence are defined in terms of the
previous item until the output is reached.

** 1.2 Mathematical Preliminaries

First this section will merely be skimmed over in order to gain rough introduction
and not necessarily and understanding of the mathematical notations and concepts
used to explain the computation ideas in further sections of the book. What they
are used for and for what purposes.

These concepts and knowledge are used for describing algorithms, algorithm analysis.
College level algebra and elementary calculus is the minimum prerequisite knowledge
required for this section.

The book `Concrete Mathematics` can be used as a more throughout learning of the
concepts at hand.

*** 1.2.1 Mathematical Induction

The basic concept of mathematical induction is that for proving a statement P(n)
for all values requires proving that a base case is true and perhaps several other
simple cases. Assuming that the P(n) is true prove that is P(n+1) is also true
since if P(n) is true then that implies that P(n+1) is true.

Using this as a base it is possible to prove the correctness of algorithm by checking
for certain conditions on the input, the output and the between all the different
that and algorithm takes to compute a value. All the intermediate steps are described
in grand set that describes an algorithm,

More than a guess a proof is a logical statement that stands on its own and can
denote correctness.

The book shows algorithm correctness proofs in order to show the thought process.
However, Donald Knuth seems to think that proofs are easy. I must try to implement
the algorithms in question whether it is in C or in MIX.

The Halting Problem is one of the great mathematical mysteries and cannot be solved
by the likes of me.

R.W Floyd states that operations in computer languages can be formulated as logical
rules that highlight assertions that can be proved. Whatever that means.
